import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/banner';
import Card from '../components/card';
import styles from '../styles/Home.module.css';
import coffeeStoresData from '../data/coffee-stores.json';
import { fetchCoffeeStores } from '../lib/coffee-stores';
import useTrackLocation from '../hooks/use-track-location';
import { useContext, useEffect, useState } from 'react';
import { ACTION_TYPES, StoreContext } from '../context/store-context';

export async function getStaticProps(context) {

  const coffeeStores = await fetchCoffeeStores();
  return {
    props: {
      coffeeStores,
    }, // will be passed to the component as props
  };
}

export default function Home(props) {
  const {dispatch , state} = useContext(StoreContext)
const {coffeeStores, latLong} = state
  const {
    handleTrackLocation,
    locationErrorMassage,
    isFindingLocation,
  } = useTrackLocation();
  //const [coffeeStores, setCoffeeStores] = useState('')
  const [coffeeStoresError, setCoffeeStoresError] = useState(null)
  const handleOnBannerButtonClick = () => {
    handleTrackLocation();
  };

  useEffect(() => {
    const a = async () => {
      if (latLong) {
        try {
          console.log(latLong);
          const response = await fetch(`/api/getCoffeStoresByLocation?latLong=${latLong}&limit=30`);
          const coffeeStores = await response.json()
          dispatch({
            type: ACTION_TYPES.SET_COFFEE_STORES,
            payload: {coffeeStores}
          })
        //  setCoffeeStores(fetchedCoffeeStores)
        } catch (error) {
          setCoffeeStoresError(error.message)
        }
      }
    };
    a()
  }, [latLong]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={isFindingLocation ? 'Loading...' : 'View stores nearby'}
          handleOnClick={handleOnBannerButtonClick}
        />
        {locationErrorMassage && (
          <p>somtthing went wrong:{locationErrorMassage} </p>
        )}
        {coffeeStoresError && (
          <p>somtthing went wrong:{coffeeStoresError} </p>
        )}
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            alt="s"
            width={700}
            height={400}
          />
        </div>


        {coffeeStores?.length > 0 && (
          <>
            <h2 className={styles.heading2}> stores near me</h2>
            <div className={styles.cardLayout}>
              {coffeeStores.map((coffeeStore) => {
                return (
                  <Card
                    key={coffeeStore.id}
                    className={styles.card}
                    name={coffeeStore.name}
                    imgUrl={
                      coffeeStore.imgUrl ||
                      'https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80'
                    }
                    href={`/coffee-store/${coffeeStore.id}`}
                  />
                );
              })}
            </div>
          </>
        )}
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>toronto stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore) => {
                return (
                  <Card
                    key={coffeeStore.id}
                    className={styles.card}
                    name={coffeeStore.name}
                    imgUrl={
                      coffeeStore.imgUrl ||
                      'https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80'
                    }
                    href={`/coffee-store/${coffeeStore.id}`}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
